[book]
authors = ["Robert Pearce"]
language = "en"
multilingual = false
src = "book_src"
title = "Ramda Guide"

[build]
create-missing = false
build-dir = "./web/book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"

[output.html.playground]
editable = false
