[package]
name = "hull"
version = "0.1.0"
authors = ["Robert Pearce <me@robertwpearce.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
handlebars = "3.5"
mdbook = "0.4"
pulldown-cmark = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
