[site]
url = "https://ramda.guide"

[posts]
source = "./src/news"
output = "./web/news"
  [posts.meta]
  title = "Ramda Guide News"
  url = "https://ramda.guide/news"

[sitemap]
enabled = true
output = "./web/sitemap.xml"
  [sitemap.posts]
  changefreq = "daily"
  priority = "0.7"

[feed]
enabled = true
output = "./web/feed.atom"
