[posts]
source = "./src/news"
output = "./web/news"
  [posts.meta]
  title = "Ramda Guide News"
  url = "https://ramda.guide/news"

[sitemap]
enabled = true
output = "./web/sitemap.xml"

[feed]
enabled = true
output = "./web/feed.atom"
