[package]
name = "news"
version = "0.1.0"
authors = ["Robert Pearce <me@robertwpearce.com>"]
edition = "2018"

[dependencies]
handlebars = "3.5"
pulldown-cmark = "0.8.0"
rss = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
