name: CI

on:
  pull_request:
  push:

jobs:
  build-nix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build with cachix
        uses: cachix/cachix-action@v12
        with:
          name: ramda-guide
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build
      - run: nix run .#hull

      - name: Artifact pages
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: web

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-nix]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pages
          path: web

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: web
          target_branch: gh-pages
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
